<?php

namespace common\models;

use common\enums\Constents;
use common\enums\PaymentMethod;
use common\enums\RequestEnums;
use common\enums\RequestTypes;
use common\models\RequestDates;
use common\models\Place;
use common\models\Product;
use Yii;


class Request extends \common\models\generated\Request
{
    public $item_name;
    public $date_range;
    public $end_date;
    public $dates;

    public function rules()
    {
        $p = parent::rules();
//        $p[] = [['imagesFile'], 'file','extensions' => 'jpg, png, jpeg, gif', 'on'=>'update'];
        $p[] = [['date_range', 'end_date', 'dates'], 'safe'];
        $p[] = [['class_period'], 'required', 'on' => 'request_class'];

        return $p;
    }

    public function attributeLabels()
    {
        $p = parent::attributeLabels();
        $p['place_id'] = t("Place");
        $p['product_id'] = t("Product");
        $p['status'] = t("Status");
        $p['phone'] = t('Phone');
        $p['price'] = t('Price');
        $p['created_date'] = t('Created Date');
        $p['fname'] = t('First Name');
        $p['lname'] = t('Last Name');
        $p['user_id'] = t('User');
        $p['enums'] = t('Type');
        $p['email'] = t('Email');
        $p['image'] = t('Image');
        $p['price_unit_number'] = t('How Many Months?');
        $p['item_name'] = t('Item Name');
        $p['payment_method'] = t('Payment Method');
        $p['start_date'] = t('Start Date');
        $p['class_period'] = t('Class Period');
        $p['date_range'] = t('Date Range');
        $p['end_date'] = t('End Date');
        return $p;
    }

    public function afterFind()
    {
        if($this->product){
            $this->item_name = $this->product->name;
        }
        if($this->place){
            $this->item_name = $this->place->name;
        }
        if($this->enums == RequestEnums::hall){
            $this->end_date = date('Y-m-d', strtotime($this->start_date . '+ '.$this->price_unit_number.' days'));
        }
        if($this->enums == RequestEnums::package){
            $this->end_date = date('Y-m-d', strtotime($this->start_date . '+ '.$this->price_unit_number.' months'));
        }

        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function getPlace()
    {
        return $this->hasOne(Place::className(), ['id' => 'place_id']);
    }

    public function getProduct()
    {
        return $this->hasOne(Product::className(), ['id' => 'product_id']);
    }

    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getIsPayed()
    {
        if($this->payment_method == PaymentMethod::paypal && $this->payment_result == 'CAPTURED'){
            return true;
        } else {
            return false;
        }
    }

    public function getRequestDates()
    {
        return $this->hasMany(RequestDates::className(), ['request_id' => 'id']);
    }

}
