<?php

namespace bedezign\yii2\audit\models;

use bedezign\yii2\audit\components\db\ActiveRecord;
use Ramsey\Uuid\Uuid;
use Yii;

/**
 * AuditError
 * @package bedezign\yii2\audit\models
 *
 * @property int           $id
 * @property int           $entry_id
 * @property string        $created
 * @property string        $message
 * @property int           $code
 * @property string        $file
 * @property int           $line
 * @property mixed         $trace
 * @property mixed         $trace_json
 * @property string        $hash
 * @property int           $emailed
 *
 * @property AuditEntry    $entry
 */
class AuditError extends ActiveRecord
{

    public static function getDb() {
        return Yii::$app->db_audit;
    }

    public function beforeSave($insert)
    {
        if(!$this->id || $this->id == 'temp'){
            $this->id = Uuid::uuid4()->toString();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @var array
     */
    protected $serializeAttributes = ['trace'];

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return '{{%audit_error}}';
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEntry()
    {
        return $this->hasOne(AuditEntry::className(), ['id' => 'entry_id']);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'        => Yii::t('audit', 'ID'),
            'entry_id'  => Yii::t('audit', 'Entry ID'),
            'created'   => Yii::t('audit', 'Created'),
            'message'   => Yii::t('audit', 'Message'),
            'code'      => Yii::t('audit', 'Error Code'),
            'file'      => Yii::t('audit', 'File'),
            'line'      => Yii::t('audit', 'Line'),
            'trace'     => Yii::t('audit', 'Trace'),
            'hash'      => Yii::t('audit', 'Hash'),
            'emailed'   => Yii::t('audit', 'Emailed'),
        ];
    }

    public function addData()
    {

        // Make sure to mark data as a large object so it gets escaped
        $data = [
            'entry_id' => $this->entry_id,
            'message' => $this->message,
            'code' => $this->code,
            'file' => $this->file,
            'line' => $this->line,
//            'trace' => $this->trace,
            'trace_json' => $this->trace_json,
            'hash' => $this->hash,
            'emailed' => $this->emailed,
            'created' => date('Y-m-d H:i:s'),
        ];
        static::getDb()->createCommand()->insert(AuditError::tableName(), $data)->execute();
    }

}
