<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ', follow this link to reset yout password:' => '',
    'Account already active' => '',
    'Account not found' => '',
    'An Email will be sent to the specified email address to allow the user to confirm and activate the account.' => '',
    'Captcha' => '',
    'Code' => '',
    'Code not found' => '',
    'Confirm' => '',
    'Confirm Account' => '',
    'E-mail confirmed' => '',
    'Email' => '',
    'Email Already in use' => '',
    'First Name' => '',
    'Hello' => '',
    'Hello, you have been registered on' => '',
    'Last Name' => '',
    'Phone' => '',
    'Register as new Teacher' => '',
    'Registration' => '',
    'Request for this email already sent' => '',
    'Reset password' => '',
    'Teacher Request for this email already sent' => '',
    'Thank you.' => '',
    'Use it to Verify your account from the following link: ' => '',
    'Your Confirmation Code is:' => '',
    'Your Reset Password Confirmation Code is: ' => '',
    'Your request is sent, You will receive an email if your request is approved' => '',
];
