<?php
namespace common\traits;
use common\helpers\DynamicaAutoShiping;
use common\models\ModelFactory;
use common\models\Queue;

/**
 * Created by PhpStorm.
 * User: Anas Mattar
 * Date: 11/23/2018
 * Time: 9:18 PM
 */

trait TraitQueue
{
    public function afterSave($insert, $changedAttributes)
    {
        $data=[];
        $items=ModelFactory::getModelForeignKeys(self::tableName());
        foreach ($this->getAttributes() as $key=>$attribute) {
            $data[$key] = $attribute;
            if (array_key_exists($key, $items)) {
                $model = ModelFactory::getModelWithOutRelation($items[$key]);

                if (!is_null($model)) {
                    $row = $model->where(['id' => $attribute])->one();
                    if ($row) {
                        $data[$key . '_symbol'] = $row->symbol;
                    }
                } else {
                    $model = ModelFactory::getModelWithRelation($items[$key]);
                    if (!is_null($model)) {
                        $row = $model->where(['id' => $attribute])->one();
                        if ($row) {
                            $data[$key . '_symbol'] = $row->symbol;
                        }
                    }
                }
            }
        }
        \Yii::$app->db->createCommand()->insert('queues',
            [
                'operation' => $insert?Queue::INSERTED:Queue::UPDATED,
                'table_name' => self::tableName(),
                'text'=>json_encode($data)
            ])
            ->execute();
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    public function afterDelete()
    {
        \Yii::$app->db->createCommand()->insert('queues',
            [
                'operation' => Queue::DELETED,
                'table_name' => self::tableName(),
                'text'=>json_encode($this->getAttributes())
            ])
            ->execute();
        parent::afterDelete(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if($insert) {
            $this->symbol = DynamicaAutoShiping::generateRandomString();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}