<?php

namespace frontend\models\user\forms;

use Yii;

class LoginForm extends \webvimark\modules\UserManagement\models\forms\LoginForm {

   public function attributeLabels()
   {
       $p = parent::attributeLabels();
       $p['email'] = t('Email');

       return $p; // TODO: Change the autogenerated stub
   }

}
