<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<b>{message}</b><br />in <i>{file}</i> on line <i>{line}</i>.<br/>-- {link}' => '',
    'Action' => '',
    'Args' => '',
    'Audit' => '',
    'Audit Error in Audit Entry #{entry_id}' => '',
    'Audit Module' => '',
    'BCC' => '',
    'CC' => '',
    'Called' => '',
    'Content' => '',
    'Content - HTML' => '',
    'Content - JSON' => '',
    'Content - Query' => '',
    'Content - XML' => '',
    'Created' => '',
    'Data' => '',
    'Diff' => '',
    'Difference' => '',
    'Download' => '',
    'Download eml file' => '',
    'Duration' => '',
    'Emailed' => '',
    'Entries' => '',
    'Entry #{id}' => '',
    'Entry ID' => '',
    'Error #{id}' => '',
    'Error Code' => '',
    'Errors' => '',
    'Extra Data' => '',
    'Field' => '',
    'File' => '',
    'From' => '',
    'Guest' => '',
    'HTML' => '',
    'HTML Body' => '',
    'Hash' => '',
    'Headers' => '',
    'ID' => '',
    'IP' => '',
    'Info' => '',
    'Javascript #{id}' => '',
    'Javascripts' => '',
    'Line' => '',
    'Log' => '',
    'Mail #{id}' => '',
    'Mails' => '',
    'Memory' => '',
    'Message' => '',
    'Model ID' => '',
    'New Value' => '',
    'No' => '',
    'Old Value' => '',
    'Origin' => '',
    'POST' => '',
    'POST - HTML' => '',
    'POST - JSON' => '',
    'POST - Query' => '',
    'POST - XML' => '',
    'Profiling' => '',
    'Reply' => '',
    'Request' => '',
    'Request #{id}' => '',
    'Request Method' => '',
    'Result' => '',
    'Result - Object' => '',
    'Result - XML' => '',
    'SOAP' => '',
    'Stack Trace' => '',
    'Subject' => '',
    'Successful' => '',
    'Text' => '',
    'Text Body' => '',
    'To' => '',
    'Trace' => '',
    'Trail #{id}' => '',
    'Trails' => '',
    'Type' => '',
    'User' => '',
    'User ID' => '',
    'Yes' => '',
    'cURL' => '',
    'view audit entry' => '',
    '{message}
in {file} on line {line}.
-- {url}' => '',
];
