<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ', follow this link to reset yout password:' => '، اتبع هذا الرابط لإعادة تعيين كلمة المرور الخاصة بك:',
    'Account already active' => 'الحساب مفعل سابقاً',
    'Account not found' => 'الحساب غير موجود',
    'An Email will be sent to the specified email address to allow the user to confirm and activate the account.' => 'سيتم إرسال بريد إلكتروني إلى عنوان البريد الإلكتروني المحدد للسماح للمستخدم بتأكيد وتنشيط الحساب.',
    'Captcha' => 'كلمة التحقق',
    'Code' => 'الرمز',
    'Code not found' => 'الرمز غير موجود',
    'Confirm' => 'تأكيد',
    'Confirm Account' => 'تأكيد حساب',
    'E-mail confirmed' => 'تم تأكيد الحساب',
    'Email' => 'البريد الإلكتروني',
    'Email Already in use' => 'البريد الإلكتروني مستخدم سابقاً',
    'First Name' => 'الاسم الأول',
    'Hello' => 'مرحباً ',
    'Hello, you have been registered on' => 'مرحباً، لقد تم تسجيلك على تطبيق ',
    'Last Name' => 'الاسم الأخير',
    'Phone' => 'الهاتف',
    'Register as new Teacher' => 'تسجيل كمدرس جديد',
    'Registration' => 'تسجيل',
    'Request for this email already sent' => 'تم إرسال طلب سابقاً لهذا البريد الإلكتروني',
    'Reset password' => 'إعادة تعيين كلمة المرور',
    'Teacher Request for this email already sent' => 'تم إرسال طلب أستاذ بهذا البريد الإلكتروني مسبقاً',
    'Thank you.' => 'شكراً لك.',
    'Use it to Verify your account from the following link: ' => 'استخدم الرمز لتأكيد حسابك من الرابط التالي: ',
    'Your Confirmation Code is:' => 'رمز التحقق الخاص بك هو: ',
    'Your Reset Password Confirmation Code is: ' => 'رمز التحقق لإعادة تعيين كلمة المرور هو: ',
    'Your request is sent, You will receive an email if your request is approved' => 'تم إرسال طلبك بنجاح، سيتم إرسال بريد إلكتروني في حال قبول الطلب',
    'Captcha' => 'كلمة التحقق',
    'Registration' => 'تسجيل',
    'Phone' => 'الهاتف',
    'Save' => 'حفظ',
    'Use it to Verify your account.' => 'استخدم الرمز لتأكيد حسابك.',
    'An Email will be sent to the specified email address to allow the user to confirm and activate the account.' => 'سيتم إرسال بريد إلكتروني إلى عنوان البريد الإلكتروني المحدد للسماح للمستخدم بتأكيد وتنشيط الحساب.',
    'Teacher Request for this email already sent' => 'تم إرسال طلب أستاذ بهذا البريد الإلكتروني مسبقاً',
    'CV' => 'السيرة الذاتية',
    'Role' => 'الدور',
    '' => '',
    '' => '',
    '' => '',
    '' => '',
];
